version: '3.8'

services:
  trading-system:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"  # Backend API on 8001
      - "8002:3000"  # Frontend on 8002
    environment:
      - PYTHONUNBUFFERED=1
      - SENTIMENT_SERVICE_URL=http://host.docker.internal:9000
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY:-demo}
    volumes:
      # Optional: mount for development (comment out for production)
      # - ./backend.py:/app/backend.py
      # - ./requirements.txt:/app/requirements.txt
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - trading-network

networks:
  trading-network:
    driver: bridge 