version: '3.8'

services:
  sentiment-analysis:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "9000:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/vertex-sa-key.json
    volumes:
      - ./logs:/app/logs
      - ./vertex-sa-key.json:/app/vertex-sa-key.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sentiment-network
      - trading-shared

networks:
  sentiment-network:
    driver: bridge
  trading-shared:
    external: true 